### ISSUE TITLE
When evaluating dress, the evaluation is displayed, but not displayed

### ISSUE THREAD

**Issue by qqbangbangbang** [google-research/composed_image_retrieval#19]
Your work is very excellent, thank you, I have encountered difficulties, I hope you can help me

python src/eval_retrieval.py  \
    --openai-pretrained  \
    --resume "composed_image_retrieval-main"   \
    --eval-mode fashion  \
    --source dress  \
    --gpu 0    \
    --model ViT-L/14

The result displayed is evaluation done

**Comment by jsjei** [comment]
Hi, I met the same question, could you please tell me how it was solved? Thanks

**Comment by 1028Bjt** [comment]
<img width="843" alt="e01be596d7353a03a24bcfe17fe3ba85" src="https://github.com/google-research/composed_image_retrieval/assets/133209590/5478d753-4ea1-4c67-a566-0cc1192256ec">
I want to know if this abnormal error is related to an input error in prompt? Why is text_tokens displayed as empty? How should we solve this problem? Waiting for your answer, good luck！
