### ISSUE TITLE
Pre-trained model availability

### ISSUE THREAD

**Issue by ojcobb** [google-research/composed_image_retrieval#2]
Hi there,

Interesting work -  thank you for sharing!

From the readme it looks like you are planning to make your trained mapping network available, but currently the Google Drive link is just a placeholder. Just wondered if you have a rough idea for when you might make this available? Trying to decide whether to train my own or be patient. :slightly_smiling_face:

**Comment by BrandonHanx** [comment]
@kihyuks @ksaito-ut 

Could you please make the pretrained MLP available? It would be great helpful!!

**Comment by ksaito-ut** [comment]
Hi, thanks for your interest. We are working on publishing the trained model. Sorry for the late.
