### ISSUE TITLE
CLIP model

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [google-research/composed_image_retrieval#3]
Hi, thanks for publishing the code, I find your work very interesting!

I have one question: which CLIP model did you use to obtain the results reported in the paper? ViT-L/14 or ViT-L/14@336px?

Thanks in advance.

**Comment by ksaito-ut** [comment]
Thanks for your interest. We used ViT-L/14.

**Comment by LorenzoAgnolucci** [comment]
Thanks!
