### ISSUE TITLE
KeyError: 'filepath' What is the format of Train_GCC-training_output.csv? 

### ISSUE THREAD

**Issue by Pter61** [google-research/composed_image_retrieval#5]
Thank you for your open source of interesting work!
Something is wrong when I attempt to run the pre-train code, which seems to fail to read my CSV file.

I use the original tsv files of cc3m. And I guess the Train_GCC-training_output.csv might be a special format, which content the path of training data (is it webdataset format for a line?, e.g., ./train/00000.tar)

```
2023-03-28,02:05:27 | INFO | Rank 0 | Use GPU: 0 for training
./composed_image_retrieval/.env3/lib/python3.7/site-packages/torchvision/transforms/transforms.py:900: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
./composed_image_retrieval/.env3/lib/python3.7/site-packages/torchvision/transforms/transforms.py:330: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
Traceback (most recent call last):
  File "src/main.py", line 338, in <module>
    main()
  File "src/main.py", line 327, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, log_queue, args))
  File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'filepath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "./composed_image_retrieval/src/main.py", line 126, in main_worker
    data = get_data(args, (preprocess_train, preprocess_val))
  File "./composed_image_retrieval/src/data.py", line 576, in get_data
    args, preprocess_train, is_train=True)
  File "./composed_image_retrieval/src/data.py", line 477, in get_csv_dataset
    sep=args.csv_separator)
  File "./composed_image_retrieval/src/data.py", line 377, in __init__
    self.images = df[img_key].tolist()
  File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/composed_image_retrieval/.env3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'filepath'
```

**Comment by jieWANGforwork** [comment]
> Thank you for your open source of interesting work! Something is wrong when I attempt to run the pre-train code, which seems to fail to read my CSV file.
> 
> I use the original tsv files of cc3m. And I guess the Train_GCC-training_output.csv might be a special format, which content the path of training data (is it webdataset format for a line?, e.g., ./train/00000.tar)
> 
> ```
> 2023-03-28,02:05:27 | INFO | Rank 0 | Use GPU: 0 for training
> ./composed_image_retrieval/.env3/lib/python3.7/site-packages/torchvision/transforms/transforms.py:900: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
>   "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
> ./composed_image_retrieval/.env3/lib/python3.7/site-packages/torchvision/transforms/transforms.py:330: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
>   "Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. "
> Traceback (most recent call last):
>   File "src/main.py", line 338, in <module>
>     main()
>   File "src/main.py", line 327, in main
>     mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, log_queue, args))
>   File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException:
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'filepath'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "./composed_image_retrieval/src/main.py", line 126, in main_worker
>     data = get_data(args, (preprocess_train, preprocess_val))
>   File "./composed_image_retrieval/src/data.py", line 576, in get_data
>     args, preprocess_train, is_train=True)
>   File "./composed_image_retrieval/src/data.py", line 477, in get_csv_dataset
>     sep=args.csv_separator)
>   File "./composed_image_retrieval/src/data.py", line 377, in __init__
>     self.images = df[img_key].tolist()
>   File "./composed_image_retrieval/.env3/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/composed_image_retrieval/.env3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> KeyError: 'filepath'
> ```

Hi,

I met the same problem, could you please tell me how it was solved? Thanks.

**Comment by zy1879046** [comment]
I also encountered the same problem. May I know how to solve it? Thanks.

**Comment by qqbangbangbang** [comment]
I also encountered the same problem. May I know how to solve it? Thanks. @Pter61
