### ISSUE TITLE
About the format of CC3M for pretraining

### ISSUE THREAD

**Issue by Natsushiro** [google-research/composed_image_retrieval#9]
Hello, thank you for sharing your exciting work. May I ask you what format of CC3M did you use for pre-training? Since the downloaded files following openclip is in a webdataset form, it seems that they cannot be directly used in your code. Again, thank you for your awesome work!

**Comment by Natsushiro** [comment]
I think this can be solved by unzipping the images and simply creating a csv file with image names and corresponding captions.

**Comment by Natsushiro** [comment]
Update:
Sorry but unzipping the images can be EXTREMELY huge. It may be better to try to implement the webdataset format.

**Comment by Natsushiro** [comment]
I tried to add the webdataset support following open_clip(https://github.com/mlfoundations/open_clip/tree/main). It seems to work, but I haven't verified the result.

**Comment by zxjia2002** [comment]
Hi! Can you successfully get the training code running?

**Comment by Natsushiro** [comment]
> Hi! Can you successfully get the training code running?

Hi! I have this code correctly running by loading the webdataset format CC3M following open_clip, but since the dataset is too large I haven’t get the final result.

**Comment by zxjia2002** [comment]
> > Hi! Can you successfully get the training code running?
> 
> Hi! I have this code correctly running by loading the webdataset format CC3M following open_clip, but since the dataset is too large I haven’t get the final result.

Thanks for your reply! I can't run the sample train code successfully with this [error](https://github.com/google-research/composed_image_retrieval/issues/11#issue-1804845517) . It seems to be wrong with loading CC3M. Did you encounter and solve this problem?

**Comment by Natsushiro** [comment]
> > > Hi! Can you successfully get the training code running?
> > 
> > 
> > Hi! I have this code correctly running by loading the webdataset format CC3M following open_clip, but since the dataset is too large I haven’t get the final result.
> 
> Thanks for your reply! I can't run the sample train code successfully with this [error](https://github.com/google-research/composed_image_retrieval/issues/11#issue-1804845517) . It seems to be wrong with loading CC3M. Did you encounter and solve this problem?

I think this is because you used CC3M as a csv format and the file cannot be recognized since the csv file of CC3M contains only the captions and the urls. My solution is to replace the data.py with the one in open_clip, and set the argument “—train-data” to the path where you download the webdataset CC3M, e.g.:

-current path
    -cc3m
        -00000.tar
        -00000_stats.json
        -00001.tar
        -00001_stats.json
        …

set to ./cc3m .

Since the code needs the number of samples in the dataset, I recommend to calculate it with the “successes” number recorded in the *_stats.json files of the downloaded dataset, since some of the samples may failed to be download due to one’s own network situation.

**Comment by zxjia2002** [comment]
@Natsushiro Thanks for your suggestions. I think problem-solving has been further advanced! But I got new errors:
my directory's structure is here:
```
 root
   ├── cc_data
            ├── train ## training image directory: *.tar,*.json,*.parquet
            └── val ## validation directory.
  ├──  cc
            ├── Train_GCC-training_output.csv ## caption and url
            └── Validation_GCC-1.1.0-Validation_output.csv ## caption and url
  ├── ...
```
Firstly, I set ```—train-data``` by .**/cc_data/train** but I got error:
![image](https://github.com/google-research/composed_image_retrieval/assets/77655043/1e63de69-9834-4aac-9b47-0057f21d31b8)
And then I tried to replace the data.py with the one in open_clip and set ```--dataset-type``` by "synthetic"
got this error:
![image](https://github.com/google-research/composed_image_retrieval/assets/77655043/c0133dbe-4f2d-4fd3-b973-58809046b3b2)
Finally, I use original data.py and set ```--dataset-type``` by "directory" but got this error:
![image](https://github.com/google-research/composed_image_retrieval/assets/77655043/7ccad99f-7a9a-461d-b3d8-1127e9a1f5c1)
However, I have seen this:
![image](https://github.com/google-research/composed_image_retrieval/assets/77655043/baa1fc4f-34e8-43d2-9627-7be3c814be94)
Does that mean the code only can use jpg images?
And where the number of samples in the dataset is used?
If it is convenient for you, please send the contact information to this email address "zxjia2002@outlook.com" so that we can communicate efficiently!

**Comment by Natsushiro** [comment]
> @Natsushiro Thanks for your suggestions. I think problem-solving has been further advanced! But I got new errors: my directory's structure is here:
> 
> ```
>  root
>    ├── cc_data
>             ├── train ## training image directory: *.tar,*.json,*.parquet
>             └── val ## validation directory.
>   ├──  cc
>             ├── Train_GCC-training_output.csv ## caption and url
>             └── Validation_GCC-1.1.0-Validation_output.csv ## caption and url
>   ├── ...
> ```
> 
> Firstly, I set `—train-data` by .**/cc_data/train** but I got error: ![image](https://user-images.githubusercontent.com/77655043/253720501-1e63de69-9834-4aac-9b47-0057f21d31b8.png) And then I tried to replace the data.py with the one in open_clip and set `--dataset-type` by "synthetic" got this error: ![image](https://user-images.githubusercontent.com/77655043/253720559-c0133dbe-4f2d-4fd3-b973-58809046b3b2.png) Finally, I use original data.py and set `--dataset-type` by "directory" but got this error: ![image](https://user-images.githubusercontent.com/77655043/253720606-7ccad99f-7a9a-461d-b3d8-1127e9a1f5c1.png) However, I have seen this: ![image](https://user-images.githubusercontent.com/77655043/253720632-baa1fc4f-34e8-43d2-9627-7be3c814be94.png) Does that mean the code only can use jpg images? And where the number of samples in the dataset is used? If it is convenient for you, please send the contact information to this email address "[zxjia2002@outlook.com](mailto:zxjia2002@outlook.com)" so that we can communicate efficiently!

Sorry I made a mistake..The path should be like this: ”./cc3m/{00000..00XXX}.tar”(XXX being the number of shards of the webdataset you download). For the Namespace error, my solution is to add the corresponding arguments in src/param.py.

**Comment by zy1879046** [comment]
> > @Natsushiro Thanks for your suggestions. I think problem-solving has been further advanced! But I got new errors: my directory's structure is here:
> > ```
> >  root
> >    ├── cc_data
> >             ├── train ## training image directory: *.tar,*.json,*.parquet
> >             └── val ## validation directory.
> >   ├──  cc
> >             ├── Train_GCC-training_output.csv ## caption and url
> >             └── Validation_GCC-1.1.0-Validation_output.csv ## caption and url
> >   ├── ...
> > ```
> > 
> > 
> > Firstly, I set `—train-data` by .**/cc_data/train** but I got error: ![image](https://user-images.githubusercontent.com/77655043/253720501-1e63de69-9834-4aac-9b47-0057f21d31b8.png) And then I tried to replace the data.py with the one in open_clip and set `--dataset-type` by "synthetic" got this error: ![image](https://user-images.githubusercontent.com/77655043/253720559-c0133dbe-4f2d-4fd3-b973-58809046b3b2.png) Finally, I use original data.py and set `--dataset-type` by "directory" but got this error: ![image](https://user-images.githubusercontent.com/77655043/253720606-7ccad99f-7a9a-461d-b3d8-1127e9a1f5c1.png) However, I have seen this: ![image](https://user-images.githubusercontent.com/77655043/253720632-baa1fc4f-34e8-43d2-9627-7be3c814be94.png) Does that mean the code only can use jpg images? And where the number of samples in the dataset is used? If it is convenient for you, please send the contact information to this email address "[zxjia2002@outlook.com](mailto:zxjia2002@outlook.com)" so that we can communicate efficiently!
> 
> Sorry I made a mistake..The path should be like this: ”./cc3m/{00000..00XXX}.tar”(XXX being the number of shards of the webdataset you download). For the Namespace error, my solution is to add the corresponding arguments in src/param.py.

I use this path”./cc3m/{00000..00XXX}.tar",but I met one problem like 
<img width="654" alt="image" src="https://github.com/google-research/composed_image_retrieval/assets/130361503/eeaad7b0-a7da-4769-aaed-838f73fa7c2f">

**Comment by qqbangbangbang** [comment]
Hi! Can you successfully get the training code running? @zy1879046

**Comment by 1028Bjt** [comment]
I also encountered the same problem. May I know how to solve it? thanks.

**Comment by Pter61** [comment]
@qqbangbangbang @1028Bjt Here is the solution~ If you find it useful, feel free to Star my repo~
